3 module resolved
js-tasks-ru/jsbasic-20230428_cherkashchenko31 pull request #5
Opened 2023-05-23 09:26 UTC by AntonCherkashchenko

2023-05-23 09:27 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-05-23 15:06 UTC, SinimaWath requested changes

2023-05-23 15:06 UTC, SinimaWath commented on 3-module/4-task/index.js
> +    return result;
Давай тут используем: `users.filter().map().join('\n')`

2023-05-24 11:05 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-05-25 11:37 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-05-26 13:18 UTC, SinimaWath approved these changes

2023-05-26 13:20 UTC, merged